---
- name: Configure Ceph RGW Multisite Sync Policy
  hosts: rgw_sync_policy_host
  become: true
  gather_facts: false

  vars:
    # Trạng thái cuối cùng của sync group (có thể là: allowed, enabled, forbidden)
    sync_group_status: "enabled"

    # Cấu hình PIPE nếu cần
    sync_pipe:
      pipe_id: "default-pipe"
      source_zones: "*"
      source_bucket: "*"
      dest_zones: "*"
      dest_bucket: "*"

  tasks:

    - name: Set default sync_group_id if not passed
      set_fact:
        effective_sync_group_id: "{{ sync_group_id | default('default-sync-group') }}"

    - name: Create sync group (if not exists)
      command: >
        radosgw-admin sync group create
        --group-id={{ effective_sync_group_id }}
        --status=allowed
      register: create_group_result
      failed_when: false
      changed_when: "'group-id' in create_group_result.stdout"

    - name: Create symmetrical flows
      when: item.flow_type == "symmetrical"
      loop: "{{ sync_flows | default([]) }}"
      loop_control:
        label: "{{ item.flow_id }}"
      command: >
        radosgw-admin sync group flow create
        --group-id={{ effective_sync_group_id }}
        --flow-id={{ item.flow_id }}
        --flow-type=symmetrical
        --zones={{ item.zones | join(',') }}

    - name: Create directional flows
      when: item.flow_type == "directional"
      loop: "{{ sync_flows | default([]) }}"
      loop_control:
        label: "{{ item.flow_id }}"
      command: >
        radosgw-admin sync group flow create
        --group-id={{ effective_sync_group_id }}
        --flow-id={{ item.flow_id }}
        --flow-type=directional
        --source-zone={{ item.source_zone }}
        --dest-zone={{ item.dest_zone }}

    - name: Create sync pipe (optional)
      when: sync_pipe is defined
      command: >
        radosgw-admin sync group pipe create
        --group-id={{ effective_sync_group_id }}
        --pipe-id={{ sync_pipe.pipe_id }}
        --source-zones='{{ sync_pipe.source_zones }}'
        --source-bucket='{{ sync_pipe.source_bucket }}'
        --dest-zones='{{ sync_pipe.dest_zones }}'
        --dest-bucket='{{ sync_pipe.dest_bucket }}'

    - name: Enable sync group
      command: >
        radosgw-admin sync group modify
        --group-id={{ effective_sync_group_id }}
        --status={{ sync_group_status }}

    - name: Commit sync policy changes
      command: radosgw-admin period update --commit
